[package]
name = "luna_modules"
version = "0.1.0"
edition = "2024"

[features]
default = ["lua54", "send", "async"]
lua55 = ["mlua/lua55", "mlua/vendored"]
lua54 = ["mlua/lua54", "mlua/vendored"]
lua53 = ["mlua/lua53", "mlua/vendored"]
lua52 = ["mlua/lua52", "mlua/vendored"]
lua51 = ["mlua/lua51", "mlua/vendored"]
luajit = ["mlua/luajit", "mlua/vendored"]
luajit52 = ["mlua/luajit52", "mlua/vendored"]
luau = ["mlua/luau", "mlua/vendored"]
luau-jit = ["mlua/luau-jit", "mlua/vendored"]
luau-vector4 = ["luau", "mlua/luau-vector4"]

send = ["mlua/send"]
serialize = ["mlua/serialize"]
async = ["mlua/async"]
macros = ["mlua/macros"]
module = ["mlua/module"]
anyhow = ["mlua/anyhow"]
error-send = ["mlua/error-send"]
userdata-wrappers = ["mlua/userdata-wrappers"]
vendored = ["mlua/vendored"]

[dependencies]
mlua = { workspace = true }
ureq = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["time", "fs", "rt", "net"] }
axum = { version = "0.8", features = ["tokio"] }
tracing = "0.1"

[dev-dependencies]
tempfile = "3"