[workspace]
members = []
resolver = "2"

[workspace.dependencies]
mlua = { version = "0.12.0", default-features = false }
thiserror = "2"
ureq = "2"
tokio = { version = "1" }

[package]
name = "luna"
version = "0.1.0"
edition = "2024"

[lib]
name = "luna"
crate-type = ["cdylib", "staticlib", "rlib"]

[[bin]]
name = "luna"
path = "src/luna/main.rs"

[features]
default = ["lua54", "send", "serialize", "async"]
lua55 = ["mlua/lua55", "mlua/vendored"]
lua54 = ["mlua/lua54", "mlua/vendored"]

send = ["mlua/send"]
serialize = ["mlua/serialize"]
async = ["mlua/async"]
macros = ["mlua/macros"]
module = ["mlua/module"]
anyhow = ["mlua/anyhow"]
error-send = ["mlua/error-send"]
userdata-wrappers = ["mlua/userdata-wrappers"]
vendored = ["mlua/vendored"]

[dependencies]
mlua = { workspace = true }
uniffi = { version = "=0.29.5", features = ["tokio", "cli"] }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "time", "fs", "rt", "net", "sync"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }
ureq = { workspace = true }
axum = { version = "0.8", features = ["tokio"] }

[target.'cfg(target_os = "android")'.dependencies]
paranoid-android = "0.2"

[dev-dependencies]
mlua = { workspace = true, features = ["vendored", "send"] }
tempfile = "3"
ureq = { workspace = true }
