-dontwarn java.awt.*
-keep class com.sun.jna.* { *; }
-keepclassmembers class * extends com.sun.jna.* { public *; }
-keep class org.siamdev.* { *; }
-keepclassmembers class * extends org.siamdev.* { public *; }