[package]
name = "luna_core"
version = "0.1.0"
edition = "2024"

[dependencies]
luna_modules = { path = "../luna_modules", default-features = false, features = ["async", "send"] }
mlua = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["rt"] }

[dev-dependencies]
mlua = { workspace = true, features = ["lua54", "vendored", "send"] }